index:
    path: /
    controller: App\Controller\HomeController::index
horoscope_show:
    path: /horoscope/show/{id}
    controller: App\Controller\ChroniqueController::show
horoscope_edit:
    path: /horoscope/edit/{id}
    controller: App\Controller\ChroniqueController::edit
horoscope_suggest:
    path: /horoscope/suggest/{category}
    controller: App\Controller\ChroniqueController::suggest